name: Build macOS .app

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: 获取项目代码
      uses: actions/checkout@v3

    - name: 安装 Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: 安装依赖
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: 编译为 .app
      run: |
        pyinstaller --noconfirm --windowed --name "ChatGPT家庭助手" main.py \
          --add-data "roles.json:." \
          --add-data "config.json:." \
          --add-data "themes:themes"

    - name: 压缩 .app
      run: |
        cd dist
        zip -r ChatGPT家庭助手.zip "ChatGPT家庭助手.app"

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v1.0.${{ github.run_number }}
        name: ChatGPT家庭助手 Build ${{ github.run_number }}
        files: dist/ChatGPT家庭助手.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
